[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#263238"
idle_fg = "#EEFFFF"
info_bg = "#89DDFF"
info_fg = "#263238"
good_bg = "#C3E88D"
good_fg = "#263238"
warning_bg = "#FFCB6B"
warning_fg = "#263238"
critical_bg = "#F07178"
critical_fg = "#263238"

[icons]
name = "awesome5"
[icons.overrides]
backlight_empty = ""
backlight_partial3 = ""
backlight_partial2 = ""
backlight_partial1 = ""
backlight_full = ""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "networkmanager"

[[block]]
block = "battery"
driver = "sysfs"
allow_missing = true
hide_missing = true

[[block]]
block = "time"
interval = 1
format = "%F %T"
