set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set number
set relativenumber
set nowrap
set ignorecase
set smartcase
set noswapfile
set nobackup
set undodir=~/.config/nvim/undodir
set undofile
set incsearch
set nohlsearch
set noshowmode
set hidden
set termguicolors
set scrolloff=8
set signcolumn=yes
set colorcolumn=120
set completeopt=menuone,noinsert,noselect
